version: '3.8'

services:
  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    image: backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=shopping_db
    networks:
      - app_network
    depends_on:
      - database

  database:
    image: database:latest
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=shopping_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
