version: '3.8'

services:
  shopping_database:
    build: ./database
    container_name: shopping_database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: shopping_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: shopping_backend
    depends_on:
      - shopping_database
    environment:
      DB_HOST: shopping_database
      DB_PORT: 3306
      DB_NAME: shopping_db
      DB_USER: root
      DB_PASSWORD: ""
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: shopping_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      DB_HOST: shopping_database
      DB_PORT: 3306
      DB_NAME: shopping_db
      DB_USER: root
      DB_PASSWORD: ""
volumes:
  mysql_data:
    driver: local
