version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
