apiVersion: v1
kind: Service
metadata:
  name: database
    #namespace: shopping-app
spec:
  ports:
    - port: 3306
  selector:
    app: database
---
apiVersion: v1
kind: Service
metadata:
  name: backend
    #namespace: shopping-app
spec:
  ports:
    - port: 5000
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
    #namespace: shopping-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: frontend

